import { byLang } from '/js/de/i18n.mjs';
/**
 * DAVRANIŞSAL FARKINDALIK METİNLERİ (Salih, 2026-10-02). Kullanıcıya gösterilen bütün yorumlar burada; koda dokunmadan
 * düzenlenebilir. {süslü parantez} içindekiler hesaplanan değerlerle doldurulur.
 *
 * İlkeler: Sistem ne yapması gerektiğini değil, ne yaptığını gösterir. Teşhis koymaz, yargılamaz, duygu tahmin etmez.
 * YASAK ifadeler: "bağımlı", "bağımlılık", "kontrolü kaybettiniz", "stresli", "öfkeli", "telafi baskısı" vb.
 * Kalıp: "Verilerinizde şu davranış görülüyor." / "Bu dönemde davranışınız değişiyor."
 */
const TR = {
    // ——— Seriler ve sonrası ———
    pattern: {
        lossStreak: 'Art arda {count} kuponunuz kaybetti.',
        winStreak: 'Art arda {count} kuponunuz kazandı.',
        returnPerception: 'Son {wins} kuponunuz kazandı. Son 7 kuponun toplamında bakiyeniz {net} coin {direction} durumda.',
        /** Seriyi tamamlayan kupon sonuçlandıktan sonra oynanan ilk 3 kuponda değişen gösterge (anlamlı değişim) */
        afterRatioUp: 'Bu {event} ardından kupon başına kullandığınız bakiye oranı arttı (%{after}, referansınız %{reference}).',
        afterRatioDown: 'Bu {event} ardından kupon başına kullandığınız bakiye oranı azaldı (%{after}, referansınız %{reference}).',
        afterGapShorter: 'Bu {event} ardından yeni kupona kadar geçen süre kısaldı ({after}, referansınız {reference}).',
        afterGapLonger: 'Bu {event} ardından yeni kupona kadar geçen süre uzadı ({after}, referansınız {reference}).',
        afterFrequencyUp: 'Bu {event} ardından 24 saatteki kupon sayınız arttı ({after}, referansınız {reference}).',
        afterFrequencyDown: 'Bu {event} ardından 24 saatteki kupon sayınız azaldı ({after}, referansınız {reference}).',
        afterSteady: 'Bu {event} ardından bakiye oranı, kupon aralığı ve sıklığınızda belirgin bir değişim görülmüyor.',
        afterPending: 'Bu {event} ardından oynanan kuponlar henüz 3 kupona ulaşmadı; değerlendirme devam ediyor.',
        /** {event} yerine geçen adlar */
        eventNames: { lossStreak: 'kayıp serisinin', winStreak: 'kazanç serisinin', returnPerception: 'kazançların' },
        directionDown: 'azalmış',
        directionUp: 'artmış',
    },
    // ——— Haftalık gelişim (son 7 gün / önceki 7 gün) ———
    weekly: {
        title: 'Haftalık Gelişim',
        coupons: 'Oynanan kupon',
        avgRatio: 'Ortalama bakiye oranı',
        previous: 'Önceki hafta: {value}',
        noCoupons: 'Son 7 günde sonuçlanmış kuponunuz yok.',
        patternsTitle: 'Seri sonrası davranış',
        noPatterns: 'Son 7 günde belirgin bir seri görülmedi.',
        noPatterns4w: 'Son 4 haftada belirgin bir seri görülmedi.',
    },
    // ——— Başlangıcınıza göre (ilk 14 gün) ———
    baseline: {
        title: 'Başlangıcınıza göre',
        note: 'İlk 14 gününüz başlangıç profiliniz olarak kaydedildi; son 7 gününüz bununla karşılaştırılır.',
        notEnough: 'Başlangıç profili için ilk 14 gününüzde en az {min} sonuçlanmış kupon gerekiyor.',
        forming: 'Başlangıç profiliniz oluşuyor (ilk 14 gün {date} tarihinde tamamlanacak).',
        changed: 'İlk haftalarınıza göre {metric} {from} değerinden {to} değerine {direction}.',
        same: 'İlk haftalarınıza göre {metric} benzer ({value}).',
        up: 'yükseldi',
        down: 'düştü',
        metrics: {
            avgRatio: 'kupon başına bakiye oranınız',
            weeklyCoupons: 'haftalık kupon sayınız',
            gapAfterLoss: 'kayıptan sonra bir sonraki kupona kadar geçen süreniz',
            avgMatches: 'kupon başına maç sayınız',
            avgOdds: 'ortalama toplam oranınız',
        },
    },
    // ——— Gün ve saat dilimi ———
    slots: {
        dayTitle: 'Gün analizi',
        hourTitle: 'Saat dilimi analizi',
        window: 'Son 4 hafta',
        coupons: 'Kupon',
        avgRatio: 'Bak. oranı',
        perWeek: 'Haftada',
        afterPattern: 'Seri sonrası',
        dataOnly: 'Yorum için bu dilimde son 4 haftada en az {min} kupon gerekiyor; şimdilik sadece veriler gösteriliyor.',
        /**
         * Sadece bakiye oranına bakar (kupon sayısına değil; bazı günler bültende çok maç olur). Yorum ve tavsiye yok, sadece veri
         * (Salih, 2026-10-07). {slot}: "Cumartesi (%2,0)", {direction}: yüksek / düşük, {overall}: son 4 haftanın genel değeri.
         */
        changedDay: '{slot} günleri kupon başına kullandığınız bakiye oranı genel değerinizden {direction} (genel %{overall}).',
        changedHour: '{slot} saatlerinde kupon başına kullandığınız bakiye oranı genel değerinizden {direction} (genel %{overall}).',
        higher: 'yüksek',
        lower: 'düşük',
        noneChanged: 'Son 4 haftada gün ve saat dilimleri arasında kupon başına bakiye oranınızda belirgin bir fark görülmüyor.',
    },
    // ——— Organizasyon takvimi ———
    calendar: {
        title: 'Organizasyon takvimi',
        note: 'Son 4 haftada kupon oynadığınız günler ve organizasyonlar',
        empty: 'Son 4 haftada organizasyon bilgisi olan kuponunuz yok.',
        unknown: 'Diğer',
    },
    // ——— Bütçe ———
    budget: {
        start: 'Başlangıç bakiyesi',
        current: 'Güncel bakiye',
        change: 'Değişim',
        updated: 'Son güncelleme: {time} · 12 saatte bir güncellenir',
        chartNote: 'Son 30 günde bakiyenizin hareketi; açık kuponlar sonuçlanınca yansır. Kesik çizgi bu ayın başlangıç bakiyesi.',
    },
    // ——— Anasayfa ve profil kartları ———
    cards: {
        budgetTitle: 'Bütçe Kontrolü',
        budgetOpen: 'Ayrıntılar',
        decisionTitle: 'Karar Analizi',
        decisionOpen: 'Gün, saat ve seri ayrıntıları',
        mostActiveDay: 'En çok kupon',
        mostActiveHour: 'En yoğun saat',
        myDataTitle: 'Kendi Verilerim',
        myDataNote: 'Geçmiş kuponlarınıza ve davranış özetlerinize hızlı erişim',
        pastCoupons: 'Geçmiş kuponlar',
        pastCouponsCount: '{count} kupon',
        patternList: 'Seri sonrası davranışlar',
        patternCount: 'Son 4 haftada {count} seri',
        habits: 'Gün, saat ve coin kullanımı',
        budgetDetail: 'Bütçe hareketleri',
        weeklySummary: 'Haftalık farkındalık özeti',
        pointsTitle: 'Puan gelişimi',
        pointsDaily: 'Gün',
        pointsMonthly: 'Ay',
        pointsDailyNote: 'Bu ay günlere göre kazanılan puan',
        pointsMonthlyNote: 'Son 12 ayda aylara göre kazanılan puan',
    },
    // ——— İstatistiklerim ———
    stats: {
        roi: 'ROI',
        winRate: 'Kazanma oranı',
        avgOdds: 'Ortalama oran',
        net: 'Net Kazanç',
        netNote: 'Güncel bakiye − bu ayın başlangıç bakiyesi',
        played: 'Oynanan',
        won: 'Kazanan',
        lost: 'Kaybeden',
        void: 'İade',
        couponsTitle: 'Kupon sayıları',
        note: 'ROI, kazanma oranı ve ortalama oran sonuçlanmış kuponlardan hesaplanır; iade kuponlar kazanma oranına ve ortalama orana girmez.',
    },
    // ——— Genel ———
    common: {
        noData: 'Henüz yeterli veri yok.',
        support: 'Destek almak isterseniz',
        supportOnline: 'çevrim içi, çok dilli',
    },
};
const EN = {
    pattern: {
        lossStreak: '{count} of your slips lost in a row.',
        winStreak: '{count} of your slips won in a row.',
        returnPerception: 'Your last {wins} slips won. Across your last 7 slips your balance is {direction} by {net} coins.',
        afterRatioUp: 'After this {event}, the share of balance you used per slip went up ({after}%, your reference {reference}%).',
        afterRatioDown: 'After this {event}, the share of balance you used per slip went down ({after}%, your reference {reference}%).',
        afterGapShorter: 'After this {event}, the time until your next slip got shorter ({after}, your reference {reference}).',
        afterGapLonger: 'After this {event}, the time until your next slip got longer ({after}, your reference {reference}).',
        afterFrequencyUp: 'After this {event}, your number of slips in 24 hours went up ({after}, your reference {reference}).',
        afterFrequencyDown: 'After this {event}, your number of slips in 24 hours went down ({after}, your reference {reference}).',
        afterSteady: 'After this {event}, there is no clear change in your balance share, slip timing or frequency.',
        afterPending: 'Fewer than 3 slips have been placed since this {event}; the evaluation is still in progress.',
        eventNames: { lossStreak: 'losing streak', winStreak: 'winning streak', returnPerception: 'run of wins' },
        directionDown: 'down',
        directionUp: 'up',
    },
    weekly: {
        title: 'Weekly Progress',
        coupons: 'Slips placed',
        avgRatio: 'Average balance share',
        previous: 'Previous week: {value}',
        noCoupons: 'You have no settled slips in the last 7 days.',
        patternsTitle: 'Behaviour after streaks',
        noPatterns: 'No clear streak in the last 7 days.',
        noPatterns4w: 'No clear streak in the last 4 weeks.',
    },
    baseline: {
        title: 'Compared with your start',
        note: 'Your first 14 days were saved as your starting profile; your last 7 days are compared with it.',
        notEnough: 'A starting profile needs at least {min} settled slips in your first 14 days.',
        forming: 'Your starting profile is being formed (your first 14 days end on {date}).',
        changed: 'Compared with your first weeks, {metric} {direction} from {from} to {to}.',
        same: 'Compared with your first weeks, {metric} is similar ({value}).',
        up: 'went up',
        down: 'went down',
        metrics: {
            avgRatio: 'your balance share per slip',
            weeklyCoupons: 'your weekly number of slips',
            gapAfterLoss: 'your time to the next slip after a loss',
            avgMatches: 'your matches per slip',
            avgOdds: 'your average total odds',
        },
    },
    slots: {
        dayTitle: 'Day analysis',
        hourTitle: 'Time-of-day analysis',
        window: 'Last 4 weeks',
        coupons: 'Slips',
        avgRatio: 'Bal. share',
        perWeek: 'Per week',
        afterPattern: 'After streaks',
        dataOnly: 'A comment needs at least {min} slips in this slot over the last 4 weeks; for now only the data is shown.',
        changedDay: 'On {slot}, the share of balance you use per slip is {direction} than your overall value (overall {overall}%).',
        changedHour: 'Between {slot}, the share of balance you use per slip is {direction} than your overall value (overall {overall}%).',
        higher: 'higher',
        lower: 'lower',
        noneChanged: 'In the last 4 weeks there is no clear difference in your balance share per slip across days and times.',
    },
    calendar: {
        title: 'Competition calendar',
        note: 'Days and competitions you placed slips on in the last 4 weeks',
        empty: 'None of your slips in the last 4 weeks have competition information.',
        unknown: 'Other',
    },
    budget: {
        start: 'Starting balance',
        current: 'Current balance',
        change: 'Change',
        updated: 'Last updated: {time} · updates every 12 hours',
        chartNote: 'Your balance over the last 30 days; open slips show once they are settled. The dashed line is this month\'s starting balance.',
    },
    cards: {
        budgetTitle: 'Budget Check',
        budgetOpen: 'Details',
        decisionTitle: 'Decision Analysis',
        decisionOpen: 'Day, time and streak details',
        mostActiveDay: 'Most slips',
        mostActiveHour: 'Busiest time',
        myDataTitle: 'My Data',
        myDataNote: 'Quick access to your past slips and behaviour summaries',
        pastCoupons: 'Past slips',
        pastCouponsCount: '{count} slips',
        patternList: 'Behaviour after streaks',
        patternCount: '{count} streaks in the last 4 weeks',
        habits: 'Days, times and coin usage',
        budgetDetail: 'Balance activity',
        weeklySummary: 'Weekly awareness summary',
        pointsTitle: 'Points progress',
        pointsDaily: 'Day',
        pointsMonthly: 'Month',
        pointsDailyNote: 'Points earned this month by day',
        pointsMonthlyNote: 'Points earned in the last 12 months by month',
    },
    stats: {
        roi: 'ROI',
        winRate: 'Win rate',
        avgOdds: 'Average odds',
        net: 'Net Gain',
        netNote: 'Current balance − this month\'s starting balance',
        played: 'Placed',
        won: 'Won',
        lost: 'Lost',
        void: 'Void',
        couponsTitle: 'Slip counts',
        note: 'ROI, win rate and average odds are calculated from settled slips; void slips are not included in win rate or average odds.',
    },
    common: {
        noData: 'Not enough data yet.',
        support: 'If you would like support',
        supportOnline: 'online, multilingual',
    },
};
const DE = {
    pattern: {
        lossStreak: '{count} deiner Tippscheine haben in Folge verloren.',
        winStreak: '{count} deiner Tippscheine haben in Folge gewonnen.',
        returnPerception: 'Deine letzten {wins} Tippscheine haben gewonnen. Über die letzten 7 Tippscheine ist dein Guthaben um {net} Coins {direction}.',
        afterRatioUp: 'Nach dieser {event} ist dein Guthabenanteil pro Tippschein gestiegen ({after} %, deine Referenz {reference} %).',
        afterRatioDown: 'Nach dieser {event} ist dein Guthabenanteil pro Tippschein gesunken ({after} %, deine Referenz {reference} %).',
        afterGapShorter: 'Nach dieser {event} wurde die Zeit bis zum nächsten Tippschein kürzer ({after}, deine Referenz {reference}).',
        afterGapLonger: 'Nach dieser {event} wurde die Zeit bis zum nächsten Tippschein länger ({after}, deine Referenz {reference}).',
        afterFrequencyUp: 'Nach dieser {event} ist deine Anzahl an Tippscheinen in 24 Stunden gestiegen ({after}, deine Referenz {reference}).',
        afterFrequencyDown: 'Nach dieser {event} ist deine Anzahl an Tippscheinen in 24 Stunden gesunken ({after}, deine Referenz {reference}).',
        afterSteady: 'Nach dieser {event} zeigt sich keine deutliche Veränderung bei Guthabenanteil, Abstand oder Häufigkeit deiner Tippscheine.',
        afterPending: 'Seit dieser {event} wurden noch keine 3 Tippscheine abgegeben; die Auswertung läuft noch.',
        eventNames: { lossStreak: 'Verlustserie', winStreak: 'Gewinnserie', returnPerception: 'Gewinnfolge' },
        directionDown: 'gesunken',
        directionUp: 'gestiegen',
    },
    weekly: {
        title: 'Wöchentliche Entwicklung',
        coupons: 'Abgegebene Tippscheine',
        avgRatio: 'Durchschnittlicher Guthabenanteil',
        previous: 'Vorwoche: {value}',
        noCoupons: 'Du hast in den letzten 7 Tagen keine abgerechneten Tippscheine.',
        patternsTitle: 'Verhalten nach Serien',
        noPatterns: 'In den letzten 7 Tagen gab es keine deutliche Serie.',
        noPatterns4w: 'In den letzten 4 Wochen gab es keine deutliche Serie.',
    },
    baseline: {
        title: 'Im Vergleich zu deinem Start',
        note: 'Deine ersten 14 Tage wurden als Startprofil gespeichert; deine letzten 7 Tage werden damit verglichen.',
        notEnough: 'Für ein Startprofil sind in deinen ersten 14 Tagen mindestens {min} abgerechnete Tippscheine nötig.',
        forming: 'Dein Startprofil entsteht (deine ersten 14 Tage enden am {date}).',
        changed: 'Im Vergleich zu deinen ersten Wochen ist {metric} von {from} auf {to} {direction}.',
        same: 'Im Vergleich zu deinen ersten Wochen ist {metric} ähnlich ({value}).',
        up: 'gestiegen',
        down: 'gesunken',
        metrics: {
            avgRatio: 'dein Guthabenanteil pro Tippschein',
            weeklyCoupons: 'deine wöchentliche Anzahl an Tippscheinen',
            gapAfterLoss: 'deine Zeit bis zum nächsten Tippschein nach einem Verlust',
            avgMatches: 'deine Anzahl an Spielen pro Tippschein',
            avgOdds: 'deine durchschnittliche Gesamtquote',
        },
    },
    slots: {
        dayTitle: 'Analyse nach Tagen',
        hourTitle: 'Analyse nach Uhrzeit',
        window: 'Letzte 4 Wochen',
        coupons: 'Tippscheine',
        avgRatio: 'Guth.-Anteil',
        perWeek: 'Pro Woche',
        afterPattern: 'Nach Serien',
        dataOnly: 'Für eine Aussage sind in diesem Abschnitt mindestens {min} Tippscheine in den letzten 4 Wochen nötig; vorerst werden nur die Daten gezeigt.',
        changedDay: 'Am {slot} ist dein Guthabenanteil pro Tippschein {direction} als dein Gesamtwert (gesamt {overall} %).',
        changedHour: 'Zwischen {slot} ist dein Guthabenanteil pro Tippschein {direction} als dein Gesamtwert (gesamt {overall} %).',
        higher: 'höher',
        lower: 'niedriger',
        noneChanged: 'In den letzten 4 Wochen gibt es zwischen Tagen und Uhrzeiten keinen deutlichen Unterschied bei deinem Guthabenanteil pro Tippschein.',
    },
    calendar: {
        title: 'Wettbewerbskalender',
        note: 'Tage und Wettbewerbe deiner Tippscheine in den letzten 4 Wochen',
        empty: 'Keiner deiner Tippscheine der letzten 4 Wochen hat Wettbewerbsangaben.',
        unknown: 'Sonstige',
    },
    budget: {
        start: 'Startguthaben',
        current: 'Aktuelles Guthaben',
        change: 'Veränderung',
        updated: 'Zuletzt aktualisiert: {time} · alle 12 Stunden',
        chartNote: 'Dein Guthaben der letzten 30 Tage; offene Tippscheine erscheinen nach der Abrechnung. Die gestrichelte Linie ist das Startguthaben dieses Monats.',
    },
    cards: {
        budgetTitle: 'Budgetkontrolle',
        budgetOpen: 'Details',
        decisionTitle: 'Entscheidungsanalyse',
        decisionOpen: 'Details zu Tagen, Uhrzeiten und Serien',
        mostActiveDay: 'Meiste Tippscheine',
        mostActiveHour: 'Aktivste Uhrzeit',
        myDataTitle: 'Meine Daten',
        myDataNote: 'Schneller Zugriff auf deine bisherigen Tippscheine und Verhaltensübersichten',
        pastCoupons: 'Bisherige Tippscheine',
        pastCouponsCount: '{count} Tippscheine',
        patternList: 'Verhalten nach Serien',
        patternCount: '{count} Serien in den letzten 4 Wochen',
        habits: 'Tage, Uhrzeiten und Coin-Nutzung',
        budgetDetail: 'Guthabenbewegungen',
        weeklySummary: 'Wöchentliche Bewusstseinsübersicht',
        pointsTitle: 'Punkteentwicklung',
        pointsDaily: 'Tag',
        pointsMonthly: 'Monat',
        pointsDailyNote: 'Punkte dieses Monats nach Tagen',
        pointsMonthlyNote: 'Punkte der letzten 12 Monate nach Monaten',
    },
    stats: {
        roi: 'ROI',
        winRate: 'Trefferquote',
        avgOdds: 'Durchschnittsquote',
        net: 'Nettogewinn',
        netNote: 'Aktuelles Guthaben − Startguthaben dieses Monats',
        played: 'Abgegeben',
        won: 'Gewonnen',
        lost: 'Verloren',
        void: 'Erstattet',
        couponsTitle: 'Anzahl der Tippscheine',
        note: 'ROI, Trefferquote und Durchschnittsquote werden aus abgerechneten Tippscheinen berechnet; erstattete Tippscheine zählen nicht zu Trefferquote und Durchschnittsquote.',
    },
    common: {
        noData: 'Noch nicht genug Daten.',
        support: 'Wenn du Unterstützung möchtest',
        supportOnline: 'online, mehrsprachig',
    },
};
const RU = {
    pattern: {
        lossStreak: '{count} ваших купона подряд проиграли.',
        winStreak: '{count} ваших купона подряд выиграли.',
        returnPerception: 'Ваши последние {wins} купона выиграли. За последние 7 купонов ваш баланс {direction} на {net} монет.',
        afterRatioUp: 'После этой {event} доля баланса на купон выросла ({after}%, ваш ориентир {reference}%).',
        afterRatioDown: 'После этой {event} доля баланса на купон снизилась ({after}%, ваш ориентир {reference}%).',
        afterGapShorter: 'После этой {event} время до следующего купона сократилось ({after}, ваш ориентир {reference}).',
        afterGapLonger: 'После этой {event} время до следующего купона увеличилось ({after}, ваш ориентир {reference}).',
        afterFrequencyUp: 'После этой {event} число купонов за 24 часа выросло ({after}, ваш ориентир {reference}).',
        afterFrequencyDown: 'После этой {event} число купонов за 24 часа снизилось ({after}, ваш ориентир {reference}).',
        afterSteady: 'После этой {event} заметных изменений в доле баланса, интервалах и частоте купонов нет.',
        afterPending: 'После этой {event} сделано меньше 3 купонов; оценка продолжается.',
        eventNames: { lossStreak: 'серии проигрышей', winStreak: 'серии выигрышей', returnPerception: 'серии выигрышей после потерь' },
        directionDown: 'уменьшился',
        directionUp: 'увеличился',
    },
    weekly: {
        title: 'Недельная динамика',
        coupons: 'Сделано купонов',
        avgRatio: 'Средняя доля баланса',
        previous: 'Прошлая неделя: {value}',
        noCoupons: 'За последние 7 дней у вас нет рассчитанных купонов.',
        patternsTitle: 'Поведение после серий',
        noPatterns: 'За последние 7 дней явных серий не было.',
        noPatterns4w: 'За последние 4 недели явных серий не было.',
    },
    baseline: {
        title: 'По сравнению с началом',
        note: 'Ваши первые 14 дней сохранены как стартовый профиль; с ним сравниваются последние 7 дней.',
        notEnough: 'Для стартового профиля нужно не менее {min} рассчитанных купонов за первые 14 дней.',
        forming: 'Стартовый профиль формируется (первые 14 дней закончатся {date}).',
        changed: 'По сравнению с первыми неделями {metric} {direction}: было {from}, стало {to}.',
        same: 'По сравнению с первыми неделями {metric} — примерно так же ({value}).',
        up: 'выросло',
        down: 'снизилось',
        metrics: {
            avgRatio: 'доля баланса на купон',
            weeklyCoupons: 'число купонов в неделю',
            gapAfterLoss: 'время до следующего купона после проигрыша',
            avgMatches: 'число матчей в купоне',
            avgOdds: 'средний общий коэффициент',
        },
    },
    slots: {
        dayTitle: 'Анализ по дням',
        hourTitle: 'Анализ по времени суток',
        window: 'Последние 4 недели',
        coupons: 'Купоны',
        avgRatio: 'Доля бал.',
        perWeek: 'В неделю',
        afterPattern: 'После серий',
        dataOnly: 'Для вывода нужно не менее {min} купонов в этом интервале за последние 4 недели; пока показаны только данные.',
        changedDay: 'По дням «{slot}» доля баланса на купон {direction}, чем в целом (в целом {overall}%).',
        changedHour: 'В интервале {slot} доля баланса на купон {direction}, чем в целом (в целом {overall}%).',
        higher: 'выше',
        lower: 'ниже',
        noneChanged: 'За последние 4 недели заметной разницы в доле баланса на купон между днями и часами нет.',
    },
    calendar: {
        title: 'Календарь турниров',
        note: 'Дни и турниры ваших купонов за последние 4 недели',
        empty: 'За последние 4 недели нет купонов с данными о турнире.',
        unknown: 'Другие',
    },
    budget: {
        start: 'Начальный баланс',
        current: 'Текущий баланс',
        change: 'Изменение',
        updated: 'Обновлено: {time} · обновляется каждые 12 часов',
        chartNote: 'Ваш баланс за последние 30 дней; открытые купоны отражаются после расчёта. Пунктир — начальный баланс этого месяца.',
    },
    cards: {
        budgetTitle: 'Контроль бюджета',
        budgetOpen: 'Подробнее',
        decisionTitle: 'Анализ решений',
        decisionOpen: 'Дни, часы и серии подробно',
        mostActiveDay: 'Больше всего купонов',
        mostActiveHour: 'Самое активное время',
        myDataTitle: 'Мои данные',
        myDataNote: 'Быстрый доступ к прошлым купонам и сводкам поведения',
        pastCoupons: 'Прошлые купоны',
        pastCouponsCount: 'Купонов: {count}',
        patternList: 'Поведение после серий',
        patternCount: 'Серий за последние 4 недели: {count}',
        habits: 'Дни, часы и использование монет',
        budgetDetail: 'Движение баланса',
        weeklySummary: 'Недельная сводка осознанности',
        pointsTitle: 'Динамика очков',
        pointsDaily: 'День',
        pointsMonthly: 'Месяц',
        pointsDailyNote: 'Очки этого месяца по дням',
        pointsMonthlyNote: 'Очки за последние 12 месяцев по месяцам',
    },
    stats: {
        roi: 'ROI',
        winRate: 'Процент побед',
        avgOdds: 'Средний коэффициент',
        net: 'Чистый результат',
        netNote: 'Текущий баланс − начальный баланс месяца',
        played: 'Сделано',
        won: 'Выиграно',
        lost: 'Проиграно',
        void: 'Возврат',
        couponsTitle: 'Количество купонов',
        note: 'ROI, процент побед и средний коэффициент считаются по рассчитанным купонам; купоны с возвратом в процент побед и средний коэффициент не входят.',
    },
    common: {
        noData: 'Пока недостаточно данных.',
        support: 'Если вам нужна поддержка',
        supportOnline: 'онлайн, на разных языках',
    },
};
const ES = {
    pattern: {
        lossStreak: '{count} de tus boletos perdieron seguidos.',
        winStreak: '{count} de tus boletos ganaron seguidos.',
        returnPerception: 'Tus últimos {wins} boletos ganaron. En tus últimos 7 boletos tu saldo ha {direction} {net} monedas.',
        afterRatioUp: 'Tras esta {event}, la parte del saldo que usas por boleto subió ({after} %, tu referencia {reference} %).',
        afterRatioDown: 'Tras esta {event}, la parte del saldo que usas por boleto bajó ({after} %, tu referencia {reference} %).',
        afterGapShorter: 'Tras esta {event}, el tiempo hasta tu siguiente boleto se acortó ({after}, tu referencia {reference}).',
        afterGapLonger: 'Tras esta {event}, el tiempo hasta tu siguiente boleto se alargó ({after}, tu referencia {reference}).',
        afterFrequencyUp: 'Tras esta {event}, tu número de boletos en 24 horas subió ({after}, tu referencia {reference}).',
        afterFrequencyDown: 'Tras esta {event}, tu número de boletos en 24 horas bajó ({after}, tu referencia {reference}).',
        afterSteady: 'Tras esta {event} no se ve un cambio claro en tu parte del saldo, el intervalo entre boletos ni la frecuencia.',
        afterPending: 'Desde esta {event} se han hecho menos de 3 boletos; la evaluación sigue en curso.',
        eventNames: { lossStreak: 'racha de derrotas', winStreak: 'racha de aciertos', returnPerception: 'serie de aciertos' },
        directionDown: 'bajado',
        directionUp: 'subido',
    },
    weekly: {
        title: 'Evolución semanal',
        coupons: 'Boletos hechos',
        avgRatio: 'Parte media del saldo',
        previous: 'Semana anterior: {value}',
        noCoupons: 'No tienes boletos resueltos en los últimos 7 días.',
        patternsTitle: 'Comportamiento tras rachas',
        noPatterns: 'No hubo ninguna racha clara en los últimos 7 días.',
        noPatterns4w: 'No hubo ninguna racha clara en las últimas 4 semanas.',
    },
    baseline: {
        title: 'Comparado con tu inicio',
        note: 'Tus primeros 14 días se guardaron como tu perfil inicial; tus últimos 7 días se comparan con él.',
        notEnough: 'Para el perfil inicial se necesitan al menos {min} boletos resueltos en tus primeros 14 días.',
        forming: 'Tu perfil inicial se está formando (tus primeros 14 días terminan el {date}).',
        changed: 'Comparado con tus primeras semanas, {metric} ha {direction} de {from} a {to}.',
        same: 'Comparado con tus primeras semanas, {metric} es similar ({value}).',
        up: 'subido',
        down: 'bajado',
        metrics: {
            avgRatio: 'tu parte del saldo por boleto',
            weeklyCoupons: 'tu número de boletos por semana',
            gapAfterLoss: 'tu tiempo hasta el siguiente boleto tras una pérdida',
            avgMatches: 'tus partidos por boleto',
            avgOdds: 'tu cuota total media',
        },
    },
    slots: {
        dayTitle: 'Análisis por días',
        hourTitle: 'Análisis por franja horaria',
        window: 'Últimas 4 semanas',
        coupons: 'Boletos',
        avgRatio: 'Parte saldo',
        perWeek: 'Por semana',
        afterPattern: 'Tras rachas',
        dataOnly: 'Para un comentario se necesitan al menos {min} boletos en esta franja en las últimas 4 semanas; por ahora solo se muestran los datos.',
        changedDay: 'Los {slot}, la parte del saldo que usas por boleto es {direction} que tu valor general (general {overall} %).',
        changedHour: 'Entre las {slot}, la parte del saldo que usas por boleto es {direction} que tu valor general (general {overall} %).',
        higher: 'mayor',
        lower: 'menor',
        noneChanged: 'En las últimas 4 semanas no hay una diferencia clara en tu parte del saldo por boleto entre días y horas.',
    },
    calendar: {
        title: 'Calendario de competiciones',
        note: 'Días y competiciones de tus boletos en las últimas 4 semanas',
        empty: 'Ninguno de tus boletos de las últimas 4 semanas tiene información de competición.',
        unknown: 'Otras',
    },
    budget: {
        start: 'Saldo inicial',
        current: 'Saldo actual',
        change: 'Cambio',
        updated: 'Última actualización: {time} · se actualiza cada 12 horas',
        chartNote: 'Tu saldo en los últimos 30 días; los boletos abiertos se reflejan al resolverse. La línea discontinua es el saldo inicial de este mes.',
    },
    cards: {
        budgetTitle: 'Control del presupuesto',
        budgetOpen: 'Detalles',
        decisionTitle: 'Análisis de decisiones',
        decisionOpen: 'Detalles de días, horas y rachas',
        mostActiveDay: 'Más boletos',
        mostActiveHour: 'Hora con más actividad',
        myDataTitle: 'Mis datos',
        myDataNote: 'Acceso rápido a tus boletos anteriores y resúmenes de comportamiento',
        pastCoupons: 'Boletos anteriores',
        pastCouponsCount: '{count} boletos',
        patternList: 'Comportamiento tras rachas',
        patternCount: '{count} rachas en las últimas 4 semanas',
        habits: 'Días, horas y uso de monedas',
        budgetDetail: 'Movimientos del saldo',
        weeklySummary: 'Resumen semanal de conciencia',
        pointsTitle: 'Evolución de puntos',
        pointsDaily: 'Día',
        pointsMonthly: 'Mes',
        pointsDailyNote: 'Puntos de este mes por día',
        pointsMonthlyNote: 'Puntos de los últimos 12 meses por mes',
    },
    stats: {
        roi: 'ROI',
        winRate: '% de aciertos',
        avgOdds: 'Cuota media',
        net: 'Ganancia neta',
        netNote: 'Saldo actual − saldo inicial de este mes',
        played: 'Hechos',
        won: 'Ganados',
        lost: 'Perdidos',
        void: 'Anulados',
        couponsTitle: 'Número de boletos',
        note: 'El ROI, el % de aciertos y la cuota media se calculan con los boletos resueltos; los boletos anulados no cuentan para el % de aciertos ni la cuota media.',
    },
    common: {
        noData: 'Todavía no hay datos suficientes.',
        support: 'Si quieres apoyo',
        supportOnline: 'en línea, multilingüe',
    },
};
export const insightTexts = byLang({ tr: TR, en: EN, de: DE, ru: RU, es: ES });
/** "{x}" yer tutucularını doldurur */
export function fill(template, values) {
    return template.replace(/\{(\w+)\}/g, (m, k) => (k in values ? String(values[k]) : m));
}
